# PlatformIO pre-build script: writes include/BuildInfo.h with the git branch,
# commit and build time, so the firmware can tell which build it is.

Import("env")

import datetime
import os
import subprocess


def git(*args):
    try:
        return subprocess.check_output(
            ("git",) + args, cwd=env["PROJECT_DIR"], stderr=subprocess.DEVNULL
        ).decode().strip()
    except Exception:
        return "unknown"


branch = git("rev-parse", "--abbrev-ref", "HEAD")
# Tag if there is one, else the short commit; "-dirty" with uncommitted changes
commit = git("describe", "--always", "--dirty", "--tags")
build_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

header = (
    "// Generated by tools/git_version.py on every build. Do not edit.\n"
    "#pragma once\n"
    '#define FW_VERSION "%s %s"\n'
    '#define FW_BUILD_TIME "%s"\n' % (branch, commit, build_time)
)

path = os.path.join(env["PROJECT_DIR"], "include", "BuildInfo.h")
with open(path, "w") as f:
    f.write(header)

print("Firmware version: %s %s (%s)" % (branch, commit, build_time))
